#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_user_reclamations:
    path: '/user/{user_id}/reclamations'
    controller: App\Controller\ReclamationController::index
app_reclamation_messages:
    path: '/reclamation/messages/{idReclamation}'
    controller: 'App\Controller\ReclamationController::messages'
login_success:
    path: /login/success
    controller: App\Controller\SecurityController::loginSuccess

send_sms:
    path: /send-sms
    controller: App\Controller\SmsTelController::sendSMS
    methods: [POST]
